
Country.create name: "Afghanistan", nationality: "Afghan"
Country.create name: "Albania", nationality: "Albanian"
Country.create name: "Algeria", nationality: "Algerian"
Country.create name: "American Samoa", nationality: "American Samoan"
Country.create name: "Andorra", nationality: "Andorran"
Country.create name: "Angola", nationality: "Angolan"
Country.create name: "Anguilla", nationality: "Anguillan"
Country.create name: "Antarctica", nationality: "Antarctic"
Country.create name: "Antigua and Barbuda", nationality: "Antiguan or Barbudan"
Country.create name: "Argentina", nationality: "Argentine"
Country.create name: "Armenia", nationality: "Armenian"
Country.create name: "Aruba", nationality: "Aruban"
Country.create name: "Australia", nationality: "Australian"
Country.create name: "Austria", nationality: "Austrian"
Country.create name: "Azerbaijan", nationality: "Azerbaijani, Azeri"
Country.create name: "Bahamas", nationality: "Bahamian"
Country.create name: "Bahrain", nationality: "Bahraini"
Country.create name: "Bangladesh", nationality: "Bangladeshi"
Country.create name: "Barbados", nationality: "Barbadian"
Country.create name: "Belarus", nationality: "Belarusian"
Country.create name: "Belgium", nationality: "Belgian"
Country.create name: "Belize", nationality: "Belizean"
Country.create name: "Benin", nationality: "Beninese, Beninois"
Country.create name: "Bermuda", nationality: "Bermudian, Bermudan"
Country.create name: "Bhutan", nationality: "Bhutanese"
Country.create name: "Bolivia (Plurinational State of)", nationality: "Bolivian"
Country.create name: "Bonaire, Sint Eustatius and Saba", nationality: "Bonaire"
Country.create name: "Bosnia and Herzegovina", nationality: "Bosnian or Herzegovinian"
Country.create name: "Botswana", nationality: "Motswana, Botswanan"
Country.create name: "Bouvet Island", nationality: "Bouvet Island"
Country.create name: "Brazil", nationality: "Brazilian"
Country.create name: "British Indian Ocean Territory", nationality: "BIOT"
Country.create name: "Brunei Darussalam", nationality: "Bruneian"
Country.create name: "Bulgaria", nationality: "Bulgarian"
Country.create name: "Burkina Faso", nationality: "Burkinabe"
Country.create name: "Burundi", nationality: "Burundian"
Country.create name: "Cabo Verde", nationality: "Cabo Verdean"
Country.create name: "Cambodia", nationality: "Cambodian"
Country.create name: "Cameroon", nationality: "Cameroonian"
Country.create name: "Canada", nationality: "Canadian"
Country.create name: "Cayman Islands", nationality: "Caymanian"
Country.create name: "Central African Republic", nationality: "Central African"
Country.create name: "Chad", nationality: "Chadian"
Country.create name: "Chile", nationality: "Chilean"
Country.create name: "China", nationality: "Chinese"
Country.create name: "Christmas Island", nationality: "Christmas Island"
Country.create name: "Cocos (Keeling) Islands", nationality: "Cocos Island"
Country.create name: "Colombia", nationality: "Colombian"
Country.create name: "Comoros", nationality: "Comoran, Comorian"
Country.create name: "Congo (Republic of the)", nationality: "Congolese"
Country.create name: "Congo (Democratic Republic of the)", nationality: "Congolese"
Country.create name: "Cook Islands", nationality: "Cook Island"
Country.create name: "Costa Rica", nationality: "Costa Rican"
Country.create name: "Cote d'Ivoire", nationality: "Ivorian"
Country.create name: "Croatia", nationality: "Croatian"
Country.create name: "Cuba", nationality: "Cuban"
Country.create name: "Curacao", nationality: "Curacaoan"
Country.create name: "Cyprus", nationality: "Cypriot"
Country.create name: "Czech Republic", nationality: "Czech"
Country.create name: "Denmark", nationality: "Danish"
Country.create name: "Djibouti", nationality: "Djiboutian"
Country.create name: "Dominica", nationality: "Dominican"
Country.create name: "Dominican Republic", nationality: "Dominican"
Country.create name: "Ecuador", nationality: "Ecuadorian"
Country.create name: "Egypt", nationality: "Egyptian"
Country.create name: "El Salvador", nationality: "Salvadoran"
Country.create name: "Equatorial Guinea", nationality: "Equatorial Guinean, Equatoguinean"
Country.create name: "Eritrea", nationality: "Eritrean"
Country.create name: "Estonia", nationality: "Estonian"
Country.create name: "Ethiopia", nationality: "Ethiopian"
Country.create name: "Falkland Islands (Malvinas)", nationality: "Falkland Island"
Country.create name: "Faroe Islands", nationality: "Faroese"
Country.create name: "Fiji", nationality: "Fijian"
Country.create name: "Finland", nationality: "Finnish"
Country.create name: "France", nationality: "French"
Country.create name: "French Guiana", nationality: "French Guianese"
Country.create name: "French Polynesia", nationality: "French Polynesian"
Country.create name: "French Southern Territories", nationality: "French Southern Territories"
Country.create name: "Gabon", nationality: "Gabonese"
Country.create name: "Gambia", nationality: "Gambian"
Country.create name: "Georgia", nationality: "Georgian"
Country.create name: "Germany", nationality: "German"
Country.create name: "Ghana", nationality: "Ghanaian"
Country.create name: "Gibraltar", nationality: "Gibraltar"
Country.create name: "Greece", nationality: "Greek, Hellenic"
Country.create name: "Greenland", nationality: "Greenlandic"
Country.create name: "Grenada", nationality: "Grenadian"
Country.create name: "Guadeloupe", nationality: "Guadeloupe"
Country.create name: "Guam", nationality: "Guamanian, Guambat"
Country.create name: "Guatemala", nationality: "Guatemalan"
Country.create name: "Guernsey", nationality: "Channel Island"
Country.create name: "Guinea", nationality: "Guinean"
Country.create name: "Guinea-Bissau", nationality: "Bissau-Guinean"
Country.create name: "Guyana", nationality: "Guyanese"
Country.create name: "Haiti", nationality: "Haitian"
Country.create name: "Heard Island and McDonald Islands", nationality: "Heard Island or McDonald Islands"
Country.create name: "Vatican City State", nationality: "Vatican"
Country.create name: "Honduras", nationality: "Honduran"
Country.create name: "Hong Kong", nationality: "Hong Kong, Hong Kongese"
Country.create name: "Hungary", nationality: "Hungarian, Magyar"
Country.create name: "Iceland", nationality: "Icelandic"
Country.create name: "India", nationality: "Indian"
Country.create name: "Indonesia", nationality: "Indonesian"
Country.create name: "Iran", nationality: "Iranian, Persian"
Country.create name: "Iraq", nationality: "Iraqi"
Country.create name: "Ireland", nationality: "Irish"
Country.create name: "Isle of Man", nationality: "Manx"
Country.create name: "Israel", nationality: "Israeli"
Country.create name: "Italy", nationality: "Italian"
Country.create name: "Jamaica", nationality: "Jamaican"
Country.create name: "Japan", nationality: "Japanese"
Country.create name: "Jersey", nationality: "Channel Island"
Country.create name: "Jordan", nationality: "Jordanian"
Country.create name: "Kazakhstan", nationality: "Kazakhstani, Kazakh"
Country.create name: "Kenya", nationality: "Kenyan"
Country.create name: "Kiribati", nationality: "I-Kiribati"
Country.create name: "Korea (Democratic People's Republic of)", nationality: "North Korean"
Country.create name: "Korea (Republic of)", nationality: "South Korean"
Country.create name: "Kuwait", nationality: "Kuwaiti"
Country.create name: "Kyrgyzstan", nationality: "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz"
Country.create name: "Lao People's Democratic Republic", nationality: "Lao, Laotian"
Country.create name: "Latvia", nationality: "Latvian"
Country.create name: "Lebanon", nationality: "Lebanese"
Country.create name: "Lesotho", nationality: "Basotho"
Country.create name: "Liberia", nationality: "Liberian"
Country.create name: "Libya", nationality: "Libyan"
Country.create name: "Liechtenstein", nationality: "Liechtenstein"
Country.create name: "Lithuania", nationality: "Lithuanian"
Country.create name: "Luxembourg", nationality: "Luxembourg, Luxembourgish"
Country.create name: "Macao", nationality: "Macanese, Chinese"
Country.create name: "Macedonia (the former Yugoslav Republic of)", nationality: "Macedonian"
Country.create name: "Madagascar", nationality: "Malagasy"
Country.create name: "Malawi", nationality: "Malawian"
Country.create name: "Malaysia", nationality: "Malaysian"
Country.create name: "Maldives", nationality: "Maldivian"
Country.create name: "Mali", nationality: "Malian, Malinese"
Country.create name: "Malta", nationality: "Maltese"
Country.create name: "Marshall Islands", nationality: "Marshallese"
Country.create name: "Martinique", nationality: "Martiniquais, Martinican"
Country.create name: "Mauritania", nationality: "Mauritanian"
Country.create name: "Mauritius", nationality: "Mauritian"
Country.create name: "Mayotte", nationality: "Mahoran"
Country.create name: "Mexico", nationality: "Mexican"
Country.create name: "Micronesia (Federated States of)", nationality: "Micronesian"
Country.create name: "Moldova (Republic of)", nationality: "Moldovan"
Country.create name: "Monaco", nationality: "Monacan"
Country.create name: "Mongolia", nationality: "Mongolian"
Country.create name: "Montenegro", nationality: "Montenegrin"
Country.create name: "Montserrat", nationality: "Montserratian"
Country.create name: "Morocco", nationality: "Moroccan"
Country.create name: "Mozambique", nationality: "Mozambican"
Country.create name: "Myanmar", nationality: "Burmese"
Country.create name: "Namibia", nationality: "Namibian"
Country.create name: "Nauru", nationality: "Nauruan"
Country.create name: "Nepal", nationality: "Nepali, Nepalese"
Country.create name: "Netherlands", nationality: "Dutch, Netherlandic"
Country.create name: "New Caledonia", nationality: "New Caledonian"
Country.create name: "New Zealand", nationality: "New Zealand, NZ"
Country.create name: "Nicaragua", nationality: "Nicaraguan"
Country.create name: "Niger", nationality: "Nigerien"
Country.create name: "Nigeria", nationality: "Nigerian"
Country.create name: "Niue", nationality: "Niuean"
Country.create name: "Norfolk Island", nationality: "Norfolk Island"
Country.create name: "Northern Mariana Islands", nationality: "Northern Marianan"
Country.create name: "Norway", nationality: "Norwegian"
Country.create name: "Oman", nationality: "Omani"
Country.create name: "Pakistan", nationality: "Pakistani"
Country.create name: "Palau", nationality: "Palauan"
Country.create name: "Palestine, State of", nationality: "Palestinian"
Country.create name: "Panama", nationality: "Panamanian"
Country.create name: "Papua New Guinea", nationality: "Papua New Guinean, Papuan"
Country.create name: "Paraguay", nationality: "Paraguayan"
Country.create name: "Peru", nationality: "Peruvian"
Country.create name: "Philippines", nationality: "Philippine, Filipino"
Country.create name: "Pitcairn", nationality: "Pitcairn Island"
Country.create name: "Poland", nationality: "Polish"
Country.create name: "Portugal", nationality: "Portuguese"
Country.create name: "Puerto Rico", nationality: "Puerto Rican"
Country.create name: "Qatar", nationality: "Qatari"
Country.create name: "Reunion", nationality: "Reunionese, Reunionnais"
Country.create name: "Romania", nationality: "Romanian"
Country.create name: "Russian Federation", nationality: "Russian"
Country.create name: "Rwanda", nationality: "Rwandan"
Country.create name: "Saint Barthelemy", nationality: "Barthelemois"
Country.create name: "Saint Helena, Ascension and Tristan da Cunha", nationality: "Saint Helenian"
Country.create name: "Saint Kitts and Nevis", nationality: "Kittitian or Nevisian"
Country.create name: "Saint Lucia", nationality: "Saint Lucian"
Country.create name: "Saint Martin (French part)", nationality: "Saint-Martinoise"
Country.create name: "Saint Pierre and Miquelon", nationality: "Saint-Pierrais or Miquelonnais"
Country.create name: "Saint Vincent and the Grenadines", nationality: "Saint Vincentian, Vincentian"
Country.create name: "Samoa", nationality: "Samoan"
Country.create name: "San Marino", nationality: "Sammarinese"
Country.create name: "Sao Tome and Principe", nationality: "Sao Tomean"
Country.create name: "Saudi Arabia", nationality: "Saudi, Saudi Arabian"
Country.create name: "Senegal", nationality: "Senegalese"
Country.create name: "Serbia", nationality: "Serbian"
Country.create name: "Seychelles", nationality: "Seychellois"
Country.create name: "Sierra Leone", nationality: "Sierra Leonean"
Country.create name: "Singapore", nationality: "Singaporean"
Country.create name: "Sint Maarten (Dutch part)", nationality: "Sint Maarten"
Country.create name: "Slovakia", nationality: "Slovak"
Country.create name: "Slovenia", nationality: "Slovenian, Slovene"
Country.create name: "Solomon Islands", nationality: "Solomon Island"
Country.create name: "Somalia", nationality: "Somali, Somalian"
Country.create name: "South Africa", nationality: "South African"
Country.create name: "South Georgia and the South Sandwich Islands", nationality: "South Georgia or South Sandwich Islands"
Country.create name: "South Sudan", nationality: "South Sudanese"
Country.create name: "Spain", nationality: "Spanish"
Country.create name: "Sri Lanka", nationality: "Sri Lankan"
Country.create name: "Sudan", nationality: "Sudanese"
Country.create name: "Suriname", nationality: "Surinamese"
Country.create name: "Svalbard and Jan Mayen", nationality: "Svalbard"
Country.create name: "Swaziland", nationality: "Swazi"
Country.create name: "Sweden", nationality: "Swedish"
Country.create name: "Switzerland", nationality: "Swiss"
Country.create name: "Syrian Arab Republic", nationality: "Syrian"
Country.create name: "Taiwan, Province of China", nationality: "Chinese, Taiwanese"
Country.create name: "Tajikistan", nationality: "Tajikistani"
Country.create name: "Tanzania, United Republic of", nationality: "Tanzanian"
Country.create name: "Thailand", nationality: "Thai"
Country.create name: "Timor-Leste", nationality: "Timorese"
Country.create name: "Togo", nationality: "Togolese"
Country.create name: "Tokelau", nationality: "Tokelauan"
Country.create name: "Tonga", nationality: "Tongan"
Country.create name: "Trinidad and Tobago", nationality: "Trinidadian or Tobagonian"
Country.create name: "Tunisia", nationality: "Tunisian"
Country.create name: "Turkey", nationality: "Turkish"
Country.create name: "Turkmenistan", nationality: "Turkmen"
Country.create name: "Turks and Caicos Islands", nationality: "Turks and Caicos Island"
Country.create name: "Tuvalu", nationality: "Tuvaluan"
Country.create name: "Uganda", nationality: "Ugandan"
Country.create name: "Ukraine", nationality: "Ukrainian"
Country.create name: "United Arab Emirates", nationality: "Emirati, Emirian, Emiri"
Country.create name: "United Kingdom of Great Britain and Northern Ireland", nationality: "British, UK"
Country.create name: "United States Minor Outlying Islands", nationality: "American"
Country.create name: "United States of America", nationality: "American"
Country.create name: "Uruguay", nationality: "Uruguayan"
Country.create name: "Uzbekistan", nationality: "Uzbekistani, Uzbek"
Country.create name: "Vanuatu", nationality: "Ni-Vanuatu, Vanuatuan"
Country.create name: "Venezuela (Bolivarian Republic of)", nationality: "Venezuelan"
Country.create name: "Vietnam", nationality: "Vietnamese"
Country.create name: "Virgin Islands (British)", nationality: "British Virgin Island"
Country.create name: "Virgin Islands (U.S.)", nationality: "U.S. Virgin Island"
Country.create name: "Wallis and Futuna", nationality: "Wallis and Futuna, Wallisian or Futunan"
Country.create name: "Western Sahara", nationality: "Sahrawi, Sahrawian, Sahraouian"
Country.create name: "Yemen", nationality: "Yemeni"
Country.create name: "Zambia", nationality: "Zambian"
Country.create name: "Zimbabwe", nationality: "Zimbabwean"