default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: runahr_api_development

test:
  <<: *default
  database: runahr_api_test

production:
  <<: *default
  database: <%= ENV['RUNAHR_API_DATABASE'] %>
  username: <%= ENV['RUNAHR_API_DATABASE_USERNAME'] %>
  password: <%= ENV['RUNAHR_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['RUNAHR_API_DATABASE_HOSTNAME'] %>
  port: <%= ENV['RUNAHR_API_DATABASE_PORT'] %>